=== Mohit2316/statsopt/wp-assets/wp-content/static/techblog/2007/05/lifeonearth.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.palantirtech.com/schema/examples/lifeOnEarth"
            xmlns:tns="http://www.palantirtech.com/schema/examples/lifeOnEarth"
            elementFormDefault="qualified">
    <xsd:annotation>
        <xsd:documentation>This schema is based on alpha taxonomy, he science of describing, categorising and naming organisms.  For a good overview, see http://en.wikipedia.org/wiki/Taxon</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType name="lifeOnEarth">
        <xsd:sequence>
            <xsd:element name="domain" type="tns:domain" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="species">
        <xsd:attribute name="commonName" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="genus">
        <xsd:sequence minOccurs="0">
            <xsd:element name="species" type="tns:species" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="family">
        <xsd:sequence minOccurs="0">
            <xsd:element name="genus" type="tns:genus" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="order">
        <xsd:sequence minOccurs="0">
            <xsd:element name="family" type="tns:family" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="class">
        <xsd:sequence minOccurs="0">
            <xsd:element name="order" maxOccurs="unbounded" type="tns:order"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="phylum">
        <xsd:sequence minOccurs="0">
            <xsd:element name="class" type="tns:class" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="division">
        <xsd:sequence minOccurs="0">
            <xsd:element name="class" type="tns:class" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="kingdom">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="phylum" type="tns:phylum"></xsd:element>
            <xsd:element name="division" type="tns:division"></xsd:element>
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="domain">
        <xsd:sequence minOccurs="0">
            <xsd:element name="kingdom" type="tns:kingdom" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:element name="lifeOnEarth" type="tns:lifeOnEarth"></xsd:element>
</xsd:schema>

=== Mohit2316/statsopt/wp-assets/wp-content/static/techblog/2007/05/species-0.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:lifeOnEarth xmlns:tns="http://www.palantirtech.com/schema/examples/lifeOnEarth" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.palantirtech.com/schema/examples/lifeOnEarth lifeOnEarth.xsd ">
  <tns:domain name='Eukaryota'>
    <tns:kingdom name='Animaliia'>
      <tns:phylum name='Chordata'>
        <tns:class name='Mammalia'>
          <tns:order name='Primates'>
            <tns:family name='Hominidae'>
             <tns:genus name="Pan">
             <tns:species commonName="Chimpanzee" name="P. troglodytes"/>
                          <tns:species commonName="Bonobo" name="P. paniscus"/>
             </tns:genus>
              <tns:genus name='Homo'>
                <tns:species name='H. Sapiens' commonName="Human"/>
                                <tns:species name='H. Erectus' commonName="Upright Man"/>
                                                                <tns:species name='H. neanderthalensis' commonName="Neanderthal Man"/>
              </tns:genus>
            </tns:family>
          </tns:order>
        </tns:class>
      </tns:phylum>
      <tns:phylum name='Arthopoda'>
        <tns:class name='Insect'>
          <tns:order name='Diptera'>
            <tns:family name='Drosophilidae'>
              <tns:genus name='Drosophila'>
                <tns:species name='D. melanogaster' commonName="Fruit Fly"/>
              </tns:genus>
            </tns:family>
          </tns:order>
        </tns:class>
      </tns:phylum>
    </tns:kingdom>
    <tns:kingdom name='Plantae'>
      <tns:division name='Magnoliophyta'>
        <tns:class name='Magnoliopsida'>
          <tns:order name='Fabales'>
            <tns:family name='Fabaceae'>
              <tns:genus name='Pisum'>
                <tns:species name='P. sativum' commonName="Pea"/>
              </tns:genus>
            </tns:family>
          </tns:order>
        </tns:class>
    </tns:division>
  </tns:kingdom>
      <tns:kingdom name='Fungi'>
      <tns:phylum name='Basidiomycota'>
        <tns:class name='Homobasidiomycetae'>
          <tns:order name='Agaricales'>
            <tns:family name='Amanitaceae'>
              <tns:genus name='Amanita'>
                <tns:species name='A. muscaria' commonName="Fly Agaric"/>
              </tns:genus>
            </tns:family>
          </tns:order>
        </tns:class>
      </tns:phylum>
  </tns:kingdom>
</tns:domain>
 <tns:domain name='Bacteria'>
    <tns:kingdom name='Monera'>
      <tns:phylum name='Proteobacteria'>
        <tns:class name='Proteobacteria'>
          <tns:order name='Enterobacteriales'>
            <tns:family name='Enterobacteriaceae'>
              <tns:genus name='Escherichia'>
                <tns:species name='E. coli' commonName="E. coli"/>
              </tns:genus>
            </tns:family>
          </tns:order>
        </tns:class>
      </tns:phylum>
      </tns:kingdom>
      </tns:domain>
</tns:lifeOnEarth>
